# Generated by Django 3.2.4 on 2021-07-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
