# Generated by Django 3.2.4 on 2021-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210721_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default=0, max_length=35),
            preserve_default=False,
        ),
    ]
